# Git
abbr -a -- ga 'git add -u'
abbr -a -- gaa 'git add --all'
abbr -a -- gb 'git branch'
abbr -a -- gca 'git commit --amend --no-edit'
abbr -a -- gcl 'git clone'
abbr -a -- gcm 'git commit -m'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- gcpa 'git cherry-pick --abort'
abbr -a -- gcpc 'git cherry-pick --continue'
abbr -a -- gf 'git fetch'
abbr -a -- gl 'git l'
abbr -a -- gla 'git la'
abbr -a -- gp 'git push'
abbr -a -- gpl 'git pull --autostash'
abbr -a -- grb 'git rebase -i'
abbr -a -- grba 'git rebase --abort'
abbr -a -- grbc 'git rebase --continue'
abbr -a -- gs 'git status'
abbr -a -- gst 'git stash push -um'
abbr -a -- gsta 'git stash apply'
abbr -a -- gstl 'git stash list'
abbr -a -- gstp 'git stash pop'
abbr -a -- gsw 'git switch'

# Docker
abbr -a -- docc 'docker compose'
